### ISSUE TITLE
Generated query for console is commented that leads to NO

### ISSUE THREAD

**Issue by ivan-shevtsov** [aileftech/snap-admin#39]
Empty spring boot 3.1.5 application with -web and -data-jpa starters.
Database: postgresql
Snapadmin: 0.2.0

after launching I can see entity has been scanned and available at /admin.
but Console does not work, since thrown exception 'org.postgresql.util.PSQLException' is not translated to TransientDataAccessResourceException.

I was able to address the issue by putting https://github.com/spring-projects/spring-framework/blob/main/spring-jdbc/src/main/resources/org/springframework/jdbc/support/sql-error-codes.xml with
```
        <property name="transientDataAccessResourceCodes">
            <value>02000</value>
        </property>
```
but, maybe it make sense not to fall on initial (generated) sql... or at least somehow to show error on UI.

**Comment by ivan-shevtsov** [comment]
@aileftech that is correct. Since jdbc driver has not got any data, it throw PSQLException and server responded with httpStatus=500. As a result, instead of Console I got a default tomcat error page

**Comment by aileftech** [comment]
This should be fixed with the latest commit on the `dev` branch.
